// angular/src/app/gamemenu.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'

@Component({
  selector: 'menu',
  template: `
  <div>
    <h2>Welcome!</h2>
    <p>Type in your username:</p>
    <input type='text' (input)="on_name_change.emit($event.target.value)" />
    <p>First, specify your role</p>
    <button [disabled]="p_disabled" (click)="on_join_players.emit()">Player</button>
    <button [disabled]="v_disabled" (click)="on_join_voters.emit()">Voter</button>
  </div>
  `
})

export class GameMenuComponent {
  @Input() p_disabled: boolean
  @Input() v_disabled: boolean
  @Output() on_name_change = new EventEmitter<string>()
  @Output() on_join_players = new EventEmitter()
  @Output() on_join_voters = new EventEmitter()
}

// vue/src/components/GameMenu.vue
<template>
  <div>
    <h2>Welcome!</h2>
    <p>Type in your username:</p>
    <input type='text' v-on:input="$emit('on_name_change', $event.target.value)" />
    <p>First, specify your role</p>
    <button :disabled="p_disabled" v-on:click="$emit('on_join_players')">Player</button>
    <button :disabled="v_disabled" v-on:click="$emit('on_join_voters')">Voter</button>
  </div>
</template>

<script>
export default{
  props: ['p_disabled', 'v_disabled']
}
</script>
