// svelte/src/SubjectForm.svelte
<form on:submit|preventDefault={submit}>
	<h2>Add subject</h2>
	<Input type="textarea" label="Subject" bind:value={subject} on:input={ () => touched=true } on:blur={e=>
	checkField('subject')} placeholder="Type the drawing subject" isRequired="true" error={error} />
	<button type="submit" value="Add">Add</button>
	<button type="button" on:click={e=> dispatch('cancel')}>Cancel</button>
</form>

<script>
  import {
    minLengthValidation
  } from './validations.js'
  import { createEventDispatcher } from 'svelte'
  import Input from './Input.svelte'

  const validate = {
    subject: value => minLengthValidation(3, value)
  }

  let error = null
  let touched = false
	let subject = ''
  const dispatch = createEventDispatcher()

  function checkField(name) {
    error = null
    if (validate[name] && touched) {
      const value = subject
      error = validate[name](subject)
			console.log(error)
    }
  }

  function submit() {
    checkField('subject')
    if(!error){
      console.log("Ready to go!")
    }
  }
</script>

// vue/src/components/SubjectForm.vue
<template>
  <form @submit.prevent="onSubmit">
    <h2>Add subject</h2>
    <Input
      type="textarea"
      label="Subject"
      v-model="subject"
      placeholder="Type the drawing subject"
      isRequired="true"
      :error="error"
      @input="touched = true"
      @blur="checkField('subject')"
    />

    <input type="submit" value="Add" />
    <button @click="$emit('cancel')" type="button">Cancelar</button>
  </form>
</template>

<script>
import Input from '../forms/Input'
import { minLengthValidation } from '../forms/validations'

const validate = {
  subject: (value) => minLengthValidation(3, value)
}

export default {
  components: { Input },
  data: () => ({
    subject: '',
    error: null,
    touched: false
  }),
  methods: {
    checkField(name) {
      const error = validate[name] ? validate[name](this.subject) : null
      const nameError = this.touched ? error : null
      this.error = nameError
    },
    onSubmit() {
      this.touched = true
      this.checkField('subject')
      console.log(this.error)
      if(!this.error){
        console.log("Good to go!")
      }
    }
  }
}
</script>

<style scoped>
.form-item {
  display: flex;
  margin-bottom: 1.7rem;
}
</style>
