// vue/src/components/VoteDrawings.vue
<template>
  <div>
    <div v-for="(key, content) in game_content" :key="content">
      <h2 v-if="content !== '[object Object]'"> Players were prompted to draw a {{content}}!</h2>
      <p v-if="content !== '[object Object]'"> This is what they did: </p>
      <table>
        <tbody>
          <tr v-for="data in key" :key="data.img">
            <td><img alt="drawing" :src=data.img /></td>
            <td>
              <button :disabled="disabled[content]"
                      v-on:click="vote(content, data.from)" >
                 Vote this!
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <button v-on:click="$emit('on_finish')">Finish!</button>
  </div>
</template>

<script>
export default{
  data: () => ({
    disabled: {}
  }),

  props: ['game_content', 'votes'],

  methods: {
    vote(content, author){
      this.disabled[content] = true
      this.$emit('cast_vote', content, author)
    }
  },

  mounted: function() {
    for (let subject in this.game_content) {
      this.disabled[subject] = false
    }
  }
}
</script>

// svelte/src/VoteDrawings.svelte
<div>
  {#each Object.entries(game_content) as [key, item]}
    {#if key !== '[object Object]'}
      <h2> Players were prompted to draw a {key}!</h2>
      <p> This is what they did: </p>
      <table>
        <tbody>
          {#each item as data}
            <tr>
              <td>
                <img width=100 src={data.img} />
              </td>
              <td>
                <button disabled={disabled[key]}
                        on:click={() => (dispatch('cast_vote', {'subject' : key, 'player_name' : data.from}))} >
                   Vote this!
                </button>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
  {/each}
  <button on:click={() => (dispatch('finish'))}>Finish!</button>
</div>

<script>
  import { createEventDispatcher } from 'svelte'

  export let game_content
  export let votes
  export let disabled

  const dispatch = createEventDispatcher()
</script>
